# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567206dd5b053c2af4dcd167d5c53833b087204d937f7d57d530936554388f0b11f90cf2a9c69021d5f302153fe8a916dae68b5bc029b8578ec56c171f76d672

test:
  secret_key_base: c959afe6d40edfd586c640bb3aa6d898259f5304119c8653f398421d60e6c05e2035e79640c734df6fbea87c106a281676c54a5e499753607b8c36f209713870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
